### ISSUE TITLE
네트워크 알고리즘

### ISSUE THREAD

**Issue by Ariel-G-Lee** [kookmin-sw/2019-cap1-2019_24#2]
사진에 달린 태그를 이용해 네트워크를 그래프로 나타내기 위해서 어떤 네트워크 알고리즘을 사용할지?
-동시출현 빈도를 고려하지 않은 단순 연결 군집형성을 보일때
-형성된 군집을 따로 뽑아내어 동시 출현빈도를 통해서 더 가까운 정도를 보여줄때

**Comment by j0077** [comment]
--현재 논의된 내용--
1) user 중심으로 네트워크 그래프 생성
2) 전체 태그를 네트워크 클러스터링 하여 군집 형성
(속성이 비슷한 태그를 묶어서 몇개의 의미있는 군집으로 만들어냄)
3) clustering 후 형성된 군집내의 태그간 네트워크를 보여줌

**Comment by Ariel-G-Lee** [comment]
3. 클러스터링 형성 된 군집 내의 네트워크 
- 동시출현 빈도를 가중치로 줘서 링크의 굵기를 다르게해서 보여주기
- 출현 빈도에 따라 노드 크기를 다르게 해줘서 중심 태그를 보여주기

**Comment by Ariel-G-Lee** [comment]
network 커뮤니티 추출에 Louvain 알고리즘 사용

**Comment by Ariel-G-Lee** [comment]
전체 태그 네트워크 클러스터링
girvan_newman 보다 빠른 Louvain 알고리즘 사용

**Comment by Ariel-G-Lee** [comment]
degree centrality 사용 - 노드 가중치를 이용하여 시각화
