### ISSUE TITLE
이미지 긁어오기

### ISSUE THREAD

**Issue by MinnySon** [kookmin-sw/2019-cap1-2019_24#3]
이미지 자체를 저장할지? 이미지로 가는 경로를 저장할지?

**Comment by j0077** [comment]
-경로를 저장하는 것으로 논의됨
db에도 이미지파일의 경로를 저장하고 
객체인식, 얼굴 인식 등 여러 프로세스가 경로를 통해 이미지에 접근하여 기능을 수행할 수 있게 함
