### ISSUE TITLE
Python  -> Java(Android Studio)

### ISSUE THREAD

**Issue by MinnySon** [kookmin-sw/2019-cap1-2019_24#7]
작성하신 파이썬 코드를 안드로이드 내부에서 돌려야할 경우가 생기는데 혹시 획기적인 퍼팅 방법 있다면 추천해주세요

**Comment by Ariel-G-Lee** [comment]
파이썬으로 돌려야 하는 코드는 서버에서 그 외 코드는 자바로 변경
